// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ItemTemplate.tt/>

namespace Eco.Mods.TechTree
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using Eco.Gameplay.Blocks;
	using Eco.Gameplay.Components;
	using Eco.Gameplay.DynamicValues;
	using Eco.Gameplay.Items;
	using Eco.Gameplay.Objects;
	using Eco.Gameplay.Players;
	using Eco.Gameplay.Skills;
	using Eco.Gameplay.Settlements;
	using Eco.Gameplay.Systems;
	using Eco.Gameplay.Systems.TextLinks;
	using Eco.Shared.Localization;
	using Eco.Shared.Serialization;
	using Eco.Shared.Utils;
	using Eco.Core.Items;
	using Eco.World;
	using Eco.World.Blocks;
	using Eco.Gameplay.Pipes;
	using Eco.Core.Controller;
	using Eco.Gameplay.Items.Recipes;


	/// <summary>
	/// <para>Server side recipe definition for "Breed Angus Cow".</para>
	/// <para>More information about RecipeFamily objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.RecipeFamily.html</para>
	/// </summary>
	/// <remarks>
	/// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
	/// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
	/// </remarks>
	[RequiresSkill(typeof(RancherSkill), 2)]
	[Ecopedia("Items", "Products", subPageName: "Sheer Sheep")]
	public partial class SheerSheepRecipe : RecipeFamily
	{
		public SheerSheepRecipe()
		{
			var recipe = new Recipe();
			recipe.Init(
				name: "SheerSheep",  //noloc
				displayName: Localizer.DoStr("Sheer Sheep"),

				// Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
				// type of the item, the amount of the item, the skill required, and the talent used.
				ingredients: new List<IngredientElement>
				{
					new IngredientElement(typeof(SheepItem), 1, true),
					new IngredientElement(typeof(IronRazorItem), 1, true),
				},

				// Define our recipe output items.
				// For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
				// to create.
				items: new List<CraftingElement>
				{
					new CraftingElement<ShornWoolItem>(3)
				});
			this.Recipes = new List<Recipe> { recipe };
			this.ExperienceOnCraft = 5; // Defines how much experience is gained when crafted.

			// Defines the amount of labor required and the required skill to add labor
			this.LaborInCalories = CreateLaborInCaloriesValue(70, typeof(RancherSkill));

			// Defines our crafting time for the recipe
			this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(SheerSheepRecipe), start: 5, skillType: typeof(RancherSkill));

			// Perform pre/post initialization for user mods and initialize our recipe instance with the display name "BreedAngusCow"
			this.ModsPreInitialize();
			this.Initialize(displayText: Localizer.DoStr("Sheer Sheep"), recipeType: typeof(SheerSheepRecipe));
			this.ModsPostInitialize();

			// Register our RecipeFamily instance with the crafting system so it can be crafted.
			CraftingComponent.AddRecipe(tableType: typeof(BarnObject), recipe: this);
		}

		/// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
		partial void ModsPreInitialize();

		/// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
		partial void ModsPostInitialize();
	}

	/// <summary>
	/// <para>Server side item definition for the "BreedAngusCow" item.</para>
	/// <para>More information about Item objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.Item.html</para>
	/// </summary>
	/// <remarks>
	/// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
	/// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
	/// </remarks>
	[Serialized] // Tells the save/load system this object needs to be serialized. 
	[LocDisplayName("Sheer Sheep")] // Defines the localized name of the item.
	[Weight(2500)] // Defines how heavy Board is.
	[Ecopedia("Items", "Product", createAsSubPage: true)]
	[Tag("Sheer Sheep")]
	[Tag("Sheep")]
	[LocDescription("A Cow you can bread purley for meat production")] //The tooltip description for the item.
	public partial class SheerSheepItem : Item
	{


	}
}