// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Core.Items;
    using Eco.Core.Utils;
    using Eco.Core.Utils.AtomicAction;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Services;
    using Eco.Shared.Utils;
    using Gameplay.Systems.NewTooltip;
    using Eco.Gameplay.Items.Recipes;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>
    [Serialized]
    [LocDisplayName("Logistics Specialist")]
    [Ecopedia("Professions", "Engineering", createAsSubPage: true)]
    [RequiresSkill(typeof(BasicEngineeringSkill), 0), Tag("Engineering Specialty"), Tier(2)]
    [Tag("Specialty")]
    [Tag("Teachable")]
    public partial class LogisticsSpecialistSkill : Skill
    {
        public LocString DisplayDescription { get { return Localizer.DoStr("Logistics Specialists are masters of trade and moving product."); } }

        public override void OnLevelUp(User user)
        {
            user.Skillset.AddExperience(typeof(SelfImprovementSkill), 20, Localizer.DoStr("for leveling up another specialization."));
        }


        public static MultiplicativeStrategy MultiplicativeStrategy =
            new MultiplicativeStrategy(new float[] { 
                1,
                1 - 0.5f,
                1 - 0.55f,
                1 - 0.6f,
                1 - 0.65f,
                1 - 0.7f,
                1 - 0.75f,
                1 - 0.8f,
            });
        public override MultiplicativeStrategy MultiStrategy => MultiplicativeStrategy;

        public static AdditiveStrategy AdditiveStrategy =
            new AdditiveStrategy(new float[] { 
                0,
                0.5f,
                0.55f,
                0.6f,
                0.65f,
                0.7f,
                0.75f,
                0.8f,
            });
        public override AdditiveStrategy AddStrategy => AdditiveStrategy;
        public override int MaxLevel { get { return 7; } }
        public override int Tier { get { return 2; } }
    }

    [Serialized]
    [LocDisplayName("Logistics Specialist Book")]
    [Ecopedia("Items", "Skill Books", createAsSubPage: true)]
    public partial class LogisticsSpecialistSkillBook : SkillBook<LogisticsSpecialistSkill, LogisticsSpecialistSkillScroll> {}

    [Serialized]
    [LocDisplayName("Logistics Specialist Skill Scroll")]
    public partial class LogisticsSpecialistSkillScroll : SkillScroll<LogisticsSpecialistSkill, LogisticsSpecialistSkillBook> {}


    [RequiresSkill(typeof(BasicEngineeringSkill), 3)]
    public partial class LogisticsSpecialistSkillBookRecipe : RecipeFamily
    {
        public LogisticsSpecialistSkillBookRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                "LogisticsSpecialist",  //noloc
                Localizer.DoStr("Logistics Specialist Skill Book"),
                new List<IngredientElement>
                {
                    new IngredientElement(typeof(EngineeringResearchPaperAdvancedItem), 3, typeof(BasicEngineeringSkill)),
                },
                new List<CraftingElement>
                {
                    new CraftingElement<LogisticsSpecialistSkillBook>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.LaborInCalories = CreateLaborInCaloriesValue(1000, typeof(BasicEngineeringSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(LogisticsSpecialistSkillBookRecipe), 5, typeof(BasicEngineeringSkill));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Logistics Specialist Skill Book"), typeof(LogisticsSpecialistSkillBookRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(ResearchTableObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
